export default function Head() {
  return (
    <>
      <title>{`Clone: The Official Home Of YIFY Movies Torrent Downloads - YTS`}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}

// export default Head;
