import MainHeader from "@/components/layout/MainHeader";
import SocialMedia from "@/components/SocialMedia/SocialMedia";
import "./globals.css";

export const metadata = {
  title: "Clone: The Official Home Of YIFY Movies Torrent Downloads - YTS",
  description: "Generated by create next app",
  generator: "Next.js",
  applicationName: "YTS clone",
  referrer: "origin-when-cross-origin",
  keywords: ["yts clone", "louis marie atoluko ayariga", "marieloumar"],
  authors: [
    { name: "Louis Marie Atoluko Ayariga", url: "https://marieloumar.com" },
  ],
  colorScheme: "dark",
  creator: "Louis Marie Atoluko Ayariga",
  publisher: "Louis Marie Atoluko Ayariga",
  alternates: {},
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SocialMedia />
        <MainHeader />
        <main>{children}</main>
      </body>
    </html>
  );
}
